version: 2
jobs:
  build:
    docker: 
      - image: circleci/golang
    parallelism: 1
    environment:
      GO111MODULE: 'on'
      CGO_ENABLED: '0'
      GOOS: linux
      GOARCH: amd64
      IMAGE_NAME: j75689/slackbot
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Run Unit Tests
          command: |
            go test ./...
      - run:
          name: Build bin
          command: |
            go build -o slackbot-go
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build . -t $IMAGE_NAME:latest
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: dockerhub
          filters:
            branches:
              only: master