version: 1
kind: Message
metadata:
  name: ev
  project: ev
task:
  variables:
    Title: Would you like to play a game?
  command: 
    - find sid ${input1}
  stage:
    - type: action
      plugin: ElasticSearch6
      paramter: 
        addresses:
          - http://127.0.0.1:9200
        # user: 
        # pass:
        index: dev
        query: |-
          {
            "query": {
              "match": {
                "_id":"{{.input1}}"
              }
            }
          }

      output: result
    - type: render
      template: |
        {
          "blocks":[
            {
              "type": "context",
              "elements": [
                {
                  "type": "mrkdwn",
                  "text": "{{.Title}}"
                }
              ]
            },
              {
              "type": "context",
              "elements": [
                {
                  "type": "mrkdwn",
                  "text": "{{.result.hits.total}}"
                }
              ]
            }
          ]
        }
        

