version: 1
kind: Message
metadata:
  name: ev-test
  project: ev
task:
  variables:
    Title: Hello World
    data: Slack Bot
  command: 
    - hey
    - Hey

  stage:
    - type: render
      template: |-
        {
          "blocks":[
            {
              "type": "context",
              "elements": [
                {
                  "type": "mrkdwn",
                  "text": "{{.Title}}"
                }
              ]
            },
              {
              "type": "context",
              "elements": [
                {
                  "type": "mrkdwn",
                  "text": "{{.data}}"
                }
              ]
            }
          ]
        }
        

